version: "3.7"
services:
  db:
    image: postgres:13
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: dbuser
    networks:
      - db-network

  app:
    build: flask_app
    volumes:
      - ./flask_app/src:/code
    working_dir: /code
    restart: always
    ports:
      - 5000:5000
    links:
      - "db"
    networks:
      - db-network
      - web-network

  web:
    build: web
    restart: always
    depends_on: 
      - app
    ports:
      - 8888:80
    links:
      - "app"
    networks:
      - web-network

networks:
  db-network:
  web-network: